export enum EUiRoutes {
  Home = "",
  Avatar = "avatar",
  Accordion = "accordion",
  Autocomplete = "autocomplete",
  Button = "button",
  Breadcrumbs = "breadcrumbs",
  Checkbox = "checkbox",
  Copy = "copy",
  DocumentViewer = "documentViewer",
  DropDown = "dropDown",
  Form = "form",
  Hamburger = "hamburger",
  Icon = "icon",
  Modal = "modal",
  Portal = "portal",
  Overlay = "overlay",
  Rating = "rating",
  Slider = "slider",
  Skeleton = "skeleton",
  Scrollbar = "scrollbar",
  Select = "select",
  Sidebar = "sidebar",
  Spinner = "spinner",
  Switch = "switch",
  Tabs = "tabs",
  Tooltip = "tooltip",
  Typography = "typography",
}

export enum EMainRoutes {
  Ui = "ui",
  Hooks = "hooks",
  Contacts = "contacts",
  Others = "others",
}
